from PyQt6.QtWidgets import QWidget, QVBoxLayout
from PyQt6.QtCore import Qt, QObject
from PyQt6.QtGui import QPalette, QWheelEvent, QColor, QColorConstants, QResizeEvent, QPainter, QBrush

from .ChatPreview import ChatPreview
from ..Boxes.ScrollStack import ScrollStack


class ChatList(ScrollStack):
    def __init__(self, parent: QObject = None):
        ScrollStack.__init__(self, parent)

        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())
        self.addWidget(ChatPreview())

        self.reset()

    def reset(self):
        pass

